Vagrant.configure("2") do |config|
    config.vm.box = "centos/stream9"
    config.vm.box_version = "20250310.0"
    
    config.vm.network "private_network", ip: "192.168.56.17"
    config.vm.network "public_network"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end