
Vagrant.configure("2") do |config|

    config.vm.box = "centos/stream9"
    config.vm.box_version = "20250310.0"
  

    config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.network "public_network"
  
    # config.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
    # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end

    # config.vm.provision "shell", inline: <<-SHELL
  
    # SHELL
  end


# os Release
# cat /etc/os-release

# NAME="CentOS Stream"
# VERSION="9"
# ID="centos"
# ID_LIKE="rhel fedora"
# VERSION_ID="9"
# PLATFORM_ID="platform:el9"
# PRETTY_NAME="CentOS Stream 9"
# ANSI_COLOR="0;31"
# LOGO="fedora-logo-icon"
# CPE_NAME="cpe:/o:centos:centos:9"
# HOME_URL="https://centos.org/"
# BUG_REPORT_URL="https://issues.redhat.com/"
# REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
# REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"



# ip Addresses 
# ip addr show
# 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
#     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
#     inet 127.0.0.1/8 scope host lo
#        valid_lft forever preferred_lft forever
#     inet6 ::1/128 scope host 
#        valid_lft forever preferred_lft forever
# 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
#     link/ether 52:54:00:4f:bf:88 brd ff:ff:ff:ff:ff:ff
#     altname enp0s3
#     inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute eth0
#        valid_lft 85484sec preferred_lft 85484sec
#     inet6 fd00::5054:ff:fe4f:bf88/64 scope global dynamic mngtmpaddr 
#        valid_lft 86178sec preferred_lft 14178sec
#     inet6 fe80::5054:ff:fe4f:bf88/64 scope link 
#        valid_lft forever preferred_lft forever
# 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
#     link/ether 08:00:27:33:47:bb brd ff:ff:ff:ff:ff:ff
#     altname enp0s8
#     inet 192.168.56.10/24 brd 192.168.56.255 scope global noprefixroute eth1
#        valid_lft forever preferred_lft forever
#     inet6 fe80::a00:27ff:fe33:47bb/64 scope link 
#        valid_lft forever preferred_lft forever
# 4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
#     link/ether 08:00:27:84:b2:95 brd ff:ff:ff:ff:ff:ff
#     altname enp0s9
#     inet 192.168.1.54/24 brd 192.168.1.255 scope global dynamic noprefixroute eth2
#        valid_lft 85485sec preferred_lft 85485sec
#     inet6 fe80::a00:27ff:fe84:b295/64 scope link 
#        valid_lft forever preferred_lft forever