Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"                  

  config.vm.network "private_network", ip: "192.168.56.14"
  config.vm.network "public_network"     

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Automatically install and configure Apache + website
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install apache2 zip unzip git curl -y
    cd /var/www/html/
    curl https://www.tooplate.com/zip-templates/2132_clean_work.zip -o file.zip
    unzip file.zip -d temp_folder
    sudo mv temp_folder/*/* /var/www/html/
    sudo rm -rf temp_folder file.zip
    sudo systemctl start apache2
    sudo systemctl enable apache2
    echo "Your Setup Completed Successfully"
  SHELL
end
