Vagrant.configure("2") do |config|

    config.vm.box = "centos/stream9"
    config.vm.box_version = "20250310.0"
  

    config.vm.network "private_network", ip: "192.168.56.26"

    config.vm.network "public_network"
  
    # config.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
    # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end

    config.vm.provision "shell", inline: <<-SHELL
        sudo dnf -y update
        sudo dnf -y install dnf-plugins-core
        sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo systemctl enable --now docker
        sudo usermod -aG docker $USER
        newgrp docker
        sudo systemctl restart docker
    SHELL
  end