Vagrant.configure("2") do |config|
    config.vm.box = "centos/stream9"
    config.vm.box_version = "20250310.0"
  
    config.vm.network "private_network", ip: "192.168.56.12"  
    config.vm.network "public_network"

    # config.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
    #   vb.memory = "1024"
    # end
    
    # Provisioning the VM with a shell script 
    config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    yum install httpd zip unzip git -y
    cd /var/www/html/
    curl https://www.tooplate.com/zip-templates/2132_clean_work.zip -o file.zip
    unzip file.zip -d temp_folder
    mv temp_folder/*/* /var/www/html/
    sudo rm -rf temp_folder file.zip
    systemctl start httpd
    systemctl enable httpd
    echo "Your Setup Completed Successfully"
    SHELL
  end